### ISSUE TITLE
Can NOT reproduce the reported results of EuroSAT.

### ISSUE THREAD

**Issue by JimZAI** [muzairkhattak/multimodal-prompt-learning#28]
Hi, thank you for the nice work.

After several more attempts, we were unable to reproduce the results of the EuroSAT dataset in the paper using the same seeds and other hyper-parameters you specified. 

Please explain the reasons for this.

Best,

**Comment by JimZAI** [comment]
Concretely, Ours (**Yours**):
Base | Novel | H
90.03 (**94.07**) | 73.23 (**73.23**) | 80.77 (**82.35**)

**Comment by muzairkhattak** [comment]
Hi @JimZAI,

Thank you for showing interest in our work!

Regarding your query, can you please verify the checks below:

1) Are you using the same packages such as PyTorch version as mentioned in our I[NSTALL.md instruction file](https://github.com/muzairkhattak/multimodal-prompt-learning/blob/main/docs/INSTALL.md)?
2) Please refer to the provided pre-trained weights and particularly its log files, using which you can track down and analyze our training. The log file for our eurosat training can be [found at this link.](https://drive.google.com/drive/folders/17hzEcNBf6OrSHjej1lMemidOTg5zeMJI)

Also note that sometimes the results can fluctuate slightly on different machines even when using same configurations. I have observed this trend many times.

I hope that would be helpful. Kindly let us know if this resolves your issue!

Thank you and kind regards.

**Comment by JimZAI** [comment]
Thanks for your response! 

I'll try it.

**Comment by ChushanZhang** [comment]
@muzairkhattak Sorry to reopen this issue again.

Since I find the same promblem that I cannot reproduce the same result with same code. And I just check the link your provided, it seems shows the trainer is CoOOP instead of MaPLe? 

Any comments would be appreciated!

![image](https://github.com/muzairkhattak/multimodal-prompt-learning/assets/36417130/90ecda01-f21f-4057-a591-b28ab74ea5ff)

**Comment by muzairkhattak** [comment]
Hi @PoopBear1,

Thank you for reaching out to us!

Regarding the log files provided, kindly note that they show the training and testing history for the MaPLe architecture. The MaPLe framework during our experiments was using CoCoOp trainer, due to which it shows CoCoOp trainer. 

However, the results must not vary because of the change of trainer as both trainer trains the model identically. We could reproduce the same results with the same code provided in this repository. 


The fluctuations in results might occur due to changes in GPU machines, as we have also observed the same. Additionally, the environment and package versions should be the same as those provided in the [INSTALL.md file.](https://github.com/muzairkhattak/multimodal-prompt-learning/blob/main/docs/INSTALL.md)

I hope that would be helpful.

Thank you and kind regards!
