### ISSUE TITLE
Hello, regarding the issue of random seeds,

### ISSUE THREAD

**Issue by Nieleilei** [muzairkhattak/multimodal-prompt-learning#35]
may I ask why random seeds are set but the results are still different each time they are run?

**Comment by muzairkhattak** [comment]
Hi @Nieleilei,

Thank you for showing interest in our work!

Regarding your query, please note the following:

MaPLe uses multiple image-recognition benchmarks which all lies under the **few-shot setting** (i-e only few samples like 16-shots for each class are available for training). 

Due to the few-shot training scenario, the model final performance heavily depend on the choice/quality of the few-shots samples used for each class and results fluctuate when the samples are changed. Therefore, it is a standard practice to train model using different seeds and report the performance averaged over 3 seeds. In this case, each seed uses different few-shot samples during training. 

In our work, we train the models on 3 seeds where each seed uses different samples for each class, thus producing different results per seed. 

I hope your query is resolved. Kindly let us know if there is any further question. Thank you!
