### ISSUE TITLE
how can I use my own dataset?

### ISSUE THREAD

**Issue by fenglincong** [muzairkhattak/multimodal-prompt-learning#38]
Hi, how can I use my own dataset? Which files do I need to configure and which code do I need to change?

**Comment by muzairkhattak** [comment]
Hi @fenglincong,

Thank you for reaching out to us!

In order to use MaPLe with your own custom dataset, you need to reformat your dataset to one of the datasets which is already supported by our code-base. For example, you can reformat your image dataset in the format of caltech101 [whose instructions are provided here. ](https://github.com/muzairkhattak/multimodal-prompt-learning/blob/main/docs/DATASETS.md#caltech101) 


Additionally, you need to first generate a json file that have labels and image file paths stored in it, similar to the json file already provided for [caltech101 dataset here.](https://drive.google.com/file/d/1501r8Ber4nNKvmlFVQZ8SeUHTcdTTEqs/view?usp=sharing)

Once your dataset is ready, you can use our repository to train your model. Just make sure to use the `caltech101` name while running the scripts as it will be representing your custom dataset. 

I hope this could help!
Thank you and kind regard!

**Comment by ooza** [comment]
Hi @muzairkhattak
Thanks a lot for making this amazing work available for us!
Regarding the use of a custom dataset, should I modify something in the code datasest/caltech101.py ? Or I need just to use caltech101 when running the scripts as you suggested in the comment above?
PS: My dataset called onfire and includes two class names. I prepared the JSON file  as you recommanded. the dataset folder includes a subfolder of images and the split JSON file (similar to the Oxford_Pets)

**Comment by muzairkhattak** [comment]
Hi @ooza,

Thank you for reaching out to us!

Yes you do not need to modify anything else in the code. You just need to have your dataset in caltech101 format and have a similar JSON file. 

So you should be good to go!

Let us know incase you encounter any issue.

Thank you and kind regards!
