### ISSUE TITLE
MaPLE zero shot ability 

### ISSUE THREAD

**Issue by zbb1111** [muzairkhattak/multimodal-prompt-learning#71]
Thank you very much for your tremendous contribution. As a beginner, I am not very familiar with some aspects and I greatly need your help. I hope you have time to reply to me. Thank you!
For the clip model, I can directly use its zero shot ability to implement classification tasks on my own dataset. I would like to ask if it is also possible to directly use the trained MaPLE and then use the zero shot ability on my own dataset? What operations are required?
1.How do I need to train MaPLE, what changes do I need to make, and on what dataset do I need to train?
2. Which files do I need to use?

**Comment by muzairkhattak** [comment]
Hi @zbb1111,

Thank you for showing interest in MaPLe !

Regarding your queries, please note the following:

1) _I would like to ask if it is also possible to directly use the trained MaPLE and then use the zero shot ability on my own dataset?_
Yes you can use MaPLe to directly evaluate it on your dataset. You will only need to set up your own dataset first so that the repository can load your dataset. Please checkout previous closed issues in how you can define your own dataset in this repository. 
After that, you can simply use cross-dataset evaluation instructions [(in RUN.md](https://github.com/muzairkhattak/multimodal-prompt-learning/blob/main/docs/RUN.md)) to evaluate trained MaPLe on your own dataset.


2) _How do I need to train MaPLE, what changes do I need to make, and on what dataset do I need to train?_
Please refer to the instructions provided at [RUN.md](https://github.com/muzairkhattak/multimodal-prompt-learning/blob/main/docs/RUN.md) on training MaPLe. 

3) _Which files do I need to use?_
Again, all instructions have been provided in [RUN.md.](https://github.com/muzairkhattak/multimodal-prompt-learning/blob/main/docs/RUN.md)

Let us know if you still encounter any issue. 
Thank you and kind regards!

**Comment by muzairkhattak** [comment]
Hi @zbb1111,

I am closing the issue now. 
Feel free to reopen it if there are still any queries.
