### ISSUE TITLE
about backbone

### ISSUE THREAD

**Issue by rock5913** [muzairkhattak/multimodal-prompt-learning#73]
Hi! Thank you very much for your excellent article.
I noticed that the backbone of image encoder you chose is vit-B16. Have you ever test others like vit-L14, vit-B32, etc? If you did, did vit-L work better than vit-B16? If I want to test on them, what should I do to figure it out?
Looking forward to your generous reply from a beginner. Thank you!

**Comment by muzairkhattak** [comment]
Hi @rock5913,

Thank you for showing interest in MaPLe!

Yes we have experimented with ViT-L/14 model and its performance is better than the ViT-B/16 variant. 

In order to use ViT-L/14 model with MaPLe, you would need to do the following:

1) Add the ViT-L/14 model weight URL [from openai repository](https://github.com/openai/CLIP/blob/dcba3cb2e2827b402d2701e7e1c7d9fed8a20ef1/clip/clip.py#L38) and add it [here.](https://github.com/muzairkhattak/multimodal-prompt-learning/blob/69bce21ae8eda80ad6187534b2dce09cf6c59e17/clip/clip.py#L29)

2) Use the ViT-L/14 name [in the config file](https://github.com/muzairkhattak/multimodal-prompt-learning/blob/69bce21ae8eda80ad6187534b2dce09cf6c59e17/configs/trainers/MaPLe/vit_b16_c2_ep5_batch4_2ctx.yaml#L29) by replacing `NAME: "ViT-B/16"` with `NAME: "ViT-L/14"`.

3) The text embedding dimension sizes are different for ViT-L/14 variant (768 dimensions of the text encoder embeddings). You need to also change the dimensions of the coupling function in the MaPLe trainer [at these lines](https://github.com/muzairkhattak/multimodal-prompt-learning/blob/69bce21ae8eda80ad6187534b2dce09cf6c59e17/trainers/maple.py#L111).
 

I hope this would be helpful. Thank you and kind regards!

**Comment by muzairkhattak** [comment]
Hi @rock5913,

I am closing the issue now. 
Feel free to open it if there are still any issues.
